### ISSUE TITLE
Angular 8 issue. An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by mscmnc** [lentschi/ngx-ellipsis#36]
Hi, 
I installed the package, imported it to the module. But when Angular compiled the project, it gives these errors:

ℹ ｢wdm｣: Compiled successfully.
    
    ERROR in node_modules/ngx-ellipsis/lib/directives/ellipsis.directive.d.ts(160,17): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ngx-ellipsis/lib/directives/ellipsis.directive.d.ts(164,17): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by lentschi** [comment]
@mscmnc Thanks for raising this issue. It's fixed in `ngx-ellipsis@2.2.3`

**For reference:** I had to downgrade the lib's typescript version to `3.6.*` - see the rant at https://github.com/microsoft/TypeScript/issues/33939
With newer typescript versions it gets packaged in a way that angular <9 cannot work with.
