### ISSUE TITLE
Bug with Angular Universal

### ISSUE THREAD

**Issue by srtab** [lentschi/ngx-ellipsis#8]
Hi @lentschi,

When using this plugin with Angular Universal, i'm getting an error like this:
```javascript
TypeError: Cannot read property 'length' of undefined
    at EllipsisDirective.applyEllipsis (...)
    at EllipsisDirective.addResizeListener (...)
    at EllipsisDirective.ngAfterViewInit (...)
```

Example of applied ellipsys:
```html
<div class="description" ellipsis ellipsis-resize-detection="window">
    {{ announce.descriptionShort }}
</div>
```

By inspecting the code, i suppose that the error is happening because `originalText` is not being defined here: https://github.com/lentschi/ngx-ellipsis/blob/master/projects/ngx-ellipsis/src/lib/directives/ellipsis.directive.ts#L151. Probably `innerText` from elementRef is null on universal. 

The workaround to make it work was passing `announce.descriptionShort` using `ellipsis-content`.

Thanks.
Sandro Rodrigues

**Comment by lentschi** [comment]
@srtab Sorry for taking so long to respond - I'm not sure it will still help you, but anyhow...:

I just tried out ngx-ellipsis with angular-universal (on angular 6.0.0) and it seems to work fine.
The stack trace you posted is due to another problem:

Instead of writing

```
<div class="description" ellipsis ellipsis-resize-detection="window">
    {{ announce.descriptionShort }}
</div>
```
... use the following:
```
<div class="description" 
  ellipsis 
  ellipsis-resize-detection="window"
  [ellipsis-content]="announce.descriptionShort"></div>
```

This is explained in the `README` - I should however add a more descriptive error message ;-)
