### ISSUE TITLE
Angular v18 compatible

### ISSUE THREAD

**Issue by ferdiesletering** [lentschi/ngx-ellipsis#96]
Any plans to make the library Angular v18 compatible?

Tnx

**Comment by gitirous** [comment]
+1 for the Angular 18 upgrade, is it planned?

Are there parts known to break with Angular 18? Checked the Angular migration guide and did not find anything obvious, except for Angular guide mentioning a change on ComponentFixture.autoDetect - but not sure that is impacting the ngx-ellipsis test.

Anyhow, thanks for a great library and looking forward for news!

**Comment by petercurikjr** [comment]
as for me, the lib is working perfectly on angular 18 so far. the annoying part is you have to npm install with --legacy-peer-deps or --force flag.

**Comment by lentschi** [comment]
@ferdiesletering @gitirous @petercurikjr Fixed in version 4.1.4 - sorry for the delay.

@petercurikjr 
> the annoying part is you have to npm install with --legacy-peer-deps or --force flag.

I recommend never using those flags. If there's a lib provider as lazy as me - irresponsibly not updating their peer dependencies for months - just use [overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides) until they finally get their work done :wink: .

**Comment by petercurikjr** [comment]
@lentschi didnt hear about overrides so far. will definitely have a look. anyway, thank you so much for the update!

**Comment by lentschi** [comment]
You're welcome!

Btw. I just published `ngx-ellipsis@5.0.0` exporting `EllipsisDirective` as standalone, should you want to use it that way - see #97.
